import { useState } from 'react';

// `<BASE_URL>thumbs/<slug>.jpg` (generated by `pnpm thumbs` — docs/SITE.md "Thumbnails"),
// with a graceful fallback to a flat category-accent tile when the file 404s: an example
// added since the last thumbs run, or before the first run ever happens. Shared between
// the home page's gallery cards and the sidebar's nav-item thumbnails so the fallback
// logic (and the "what if it's missing" story) lives in exactly one place.
// BASE_URL (Vite's resolved `base`, docs/SITE.md "Deploy") always ends in "/" — "/" locally,
// "/react-three-examples/" on GitHub Pages — so this is a plain concatenation, not a join.
export function Thumb({ slug, accent, className }: { slug: string; accent: string; className: string }) {
  const [failed, setFailed] = useState(false);

  if (failed) {
    return <div className={className} style={{ background: `linear-gradient(135deg, ${accent}55, ${accent}11)` }} />;
  }
  return (
    <img
      src={`${import.meta.env.BASE_URL}thumbs/${slug}.jpg`}
      alt=""
      loading="lazy"
      onError={() => setFailed(true)}
      className={className}
    />
  );
}
